### ISSUE TITLE
[BUG] Test case org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"false"}} is flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13600]
### Describe the bug

The test case `org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"false"}}` is flaky:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([B565C22BDAF29AC0:8BD7562BB0AD6227]:0)
	at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
	at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1128)
	at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1101)
	at org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode(IndicesRequestCacheIT.java:1308)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
	Suppressed: java.lang.AssertionError
		at org.opensearch.indices.IndicesRequestCacheIT.shardDirectory(IndicesRequestCacheIT.java:1343)
		at org.opensearch.indices.IndicesRequestCacheIT.lambda$testDeleteAndCreateSameIndexShardOnSameNode$13(IndicesRequestCacheIT.java:1309)
		at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1116)
		... 41 more
```

### Related component

Search

### To Reproduce

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.IndicesRequestCacheIT" -Dtests.method="testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"false"}}" -Dtests.seed=B565C22BDAF29AC0 
```

### Expected behavior

The test must always pass

### Additional Details

**Plugins**
Standard

**Screenshots**

**Host/Environment (please complete the following information):**
 - CI

**Additional context**
- https://build.ci.opensearch.org/job/gradle-check/38474/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___search_concurrent_segment_search_enabled___false___/

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/dbwiddis) [3](https://github.com/reta/) [4](https://github.com/vikasvb90/)]
@reta Thanks for filing

**Comment by kiranprakash154** [comment]
@sgup432 this came up in the Opensearch Community meeting, will this be fixed by your PR - https://github.com/opensearch-project/OpenSearch/issues/13600 ?

**Comment by msfroh** [comment]
Still failing for me: https://build.ci.opensearch.org/job/gradle-check/38635/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___search_concurrent_segment_search_enabled___false___/

**Comment by prudhvigodithi** [comment]
FYI here are some [metrics](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2e729590-eb26-11ee-b008-6583d3dd450c',key:test_name,negate:!f,params:(query:'org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode%20%7Bp0%3D%7B%22search.concurrent_segment_search.enabled%22:%22false%22%7D%7D'),type:phrase),query:(match_phrase:(test_name:'org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode%20%7Bp0%3D%7B%22search.concurrent_segment_search.enabled%22:%22false%22%7D%7D')))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Gradle%20check%20report',viewMode:view)) regarding the failing test `Test case org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"false"}}`.

**Comment by kkewwei** [comment]
> @sgup432 this came up in the Opensearch Community meeting, will this be fixed by your PR - #13600 ?

I encountered in the #14069, If you haven't started doing it yet, I will try to solve it.
