### ISSUE TITLE
[BUG] Slack community invite does not work

### ISSUE THREAD

**Issue by pdeaudney** [opensearch-project/OpenSearch#17958]
### Describe the bug

Hello,

Attempts to join the slack community fail due to an invalid invite link.
The page https://opensearch.org/slack/ that has the invite link returns an error.

```
https://join.slack.com/t/opensearch/shared_invite/zt-2sp09njae-t1y6M6dQ3_uKjDVYkMHCyw
```

Error

```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

### Related component

Other

### To Reproduce

1. Go to https://opensearch.org/slack/
2. Click on 'Join the conversation'
3. Login to slack

### Expected behavior

1. Click on 'join the conversation'
2. Join slack community to engage with other opensearch users & developers.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by owaiskazi19** [comment]
@krisfreedain can you take a look here?

**Comment by nateynateynate** [comment]
@pdeaudney - I believe this has been addressed. Can you confirm for me? FWIW, it seems to be working for me.

**Comment by krisfreedain** [comment]
Hello @pdeaudney - I did put in a fix for this on Thursday and tested again today - can you make sure it's working for you? 

thanks

**Comment by pdeaudney** [comment]
Hi @krisfreedain, sorry for the slow follow up. Thanks for looking into this.

I have just tried again and I still get an error (using chrome & chrome + private browsing mode (extensions all off).
Using the link from https://docs.opensearch.org/slack.html

I have also disabled my network ad blocking & re-tested with browser dev tools open (I am not seeing any errors or failed network calls).

**Comment by pdeaudney** [comment]
I have managed to get signed up, just now 🤷

Thank you for who ever swapped out the invite. I will leave the issue open for now, incase you want to do something regarding the invite limits noted in my comment above (if not, I wont complain if you want to close it).

**Comment by krisfreedain** [comment]
Thanks again for the notes on this @pdeaudney - I'll close it now but will see about changing any limitations on the next Slack invite link we update with.
