### ISSUE TITLE
[BUG] Tasks not added to .tasks after upgrade from 1.3 to 2.3

### ISSUE THREAD

**Issue by MRabenda** [opensearch-project/OpenSearch#5708]
**Describe the bug**

1. I had AWS OpenSearch 1.3
2. Using Cloudformation I updated to 2.3
3. I had a lot of code that relied on `GET /_tasks/{task_id}` and now sth is broken after the upgrade. Tasks are created and in response to the query I am getting `task_id` but when I want to get details of it I am getting 404.
4. If I will run the `.tasks/_count` returned number is all the time the same `2907` which is the number probably which was there before the update (not 100% sure)
5.  List of indexes is my cluster

```
green open transfers_version_3 Y0MyC6vHQbaqISI5O2zLMA 12 1 7405154 176  7.3gb   3.6gb
green open activity_version_3  hijXZSuOQxS2kGEd1OyXTw  6 1   17074   0 37.4mb  18.7mb
green open .kibana_1           smtt79uyRTeJDUlE81a2KQ  1 1       2   0   20kb    10kb
green open .tasks              vkS0Dfg7Sq2ZxhM5XIN00A  1 1    2907  18  1.1mb 589.9kb
```

**Expected behavior**
Should be able to create new tasks and receive details about them

**Plugins**
No

**Comment by Bukhtawar** [comment]
@MRabenda not all tasks store results by default. Could you share some requests that are expected to store results at your end?

**Comment by MRabenda** [comment]
An example is `POST /transfers_version_3/_delete_by_query?wait_for_completion=false ....` 

The entire code is based on this - earlier this produced task that I was able to check. Now it is producing a task but when I am trying to get it - the response is 404.

**Comment by SamuelHassine** [comment]
Hello,

Observing the same behavior with an `update by query` task. Task is not added and does not exist after launching the update.

**Comment by MRabenda** [comment]
Response from AWS support 

```
Q -  Is no way to store information about the completed tasks in the way that we did in the previous version of OpenSearch?

A - Due to the modification of the Tasks API, and deprecation of this “.tasks” index functionality, the long running tasks are no longer stored in “.tasks” index and _tasks API only returns the current running tasks. 

Q - Whether the task that returned an error is available in the API - GET _tasks?

A - I regret to inform you that the Tasks that fail or return errors cannot be retrieved using the “GET _tasks”  API. Only the tasks that are currently running are returned as an output.
```

This change is so bad ... why we need tasks/jobs if we can not fetch results? Can someone from the project team explain how we should understand this change?

**Comment by minalsha** [comment]
@chelma, @kartg could you please provide your input with thiss. Seems that index/task is not being added post upgrade to 2.3.

**Comment by minalsha** [comment]
@MRabenda  is the domain hosted by AWS or is it on self managed cluster?

**Comment by MRabenda** [comment]
Hosted by AWS as managed service. Like I wrote in first 2 points of issue description

**Comment by ketanv3** [comment]
This looks related to https://github.com/opensearch-project/OpenSearch/issues/5376 which was fixed in open-source with https://github.com/opensearch-project/OpenSearch/pull/5412.

**Comment by dblock** [comment]
Reading #5412 it looks like this was fixed in 2.4.

@MRabenda Could you try the OSS 2.4 version to confirm? And if it works as you expect, we can close this. I don't have an ETA for Amazon Managed OpenSearch having 2.4 available, but maybe Amazon support will be able to give you a date.

**Comment by MRabenda** [comment]
I contacted AWS about that - they said that they still do not have an ETA. When I will upgrade to 2.4 (as far as I understand this has to be 2.4.1) I will let you know about this issue status. Thanks for your entire support.

**Comment by minalsha** [comment]
Closing this issue since we have fixed it in OpenSource OpenSearch 2.4. The issue will be fixed on AWS OpenSearch 2.4 end. Feel free to open the issue if it is still present in managed service 2.4.
