### ISSUE TITLE
[BUG] Opensearch 2.9.0 - Failed to initialize LogType config index and builtin log types

### ISSUE THREAD

**Issue by crazymind1337** [opensearch-project/OpenSearch#9061]
**Describe the bug**
I am trying to install the new version of opensearch on Ubuntu 20.04. But the cluster state stays at yellow.

**To Reproduce**
1. Install opensearch 2.9.0 on Ubuntu 20.04
2. configure a basic setting:
```
cluster.name: cluster
http.port: 9200
network.host: <local-ip>
node.name: test-node-1
path.data: "/var/lib/opensearch"
path.logs: "/var/log/opensearch"
plugins.security.disabled: true
transport.host: <local-ip>
transport.tcp.port: 9300
cluster.initial_cluster_manager_nodes: test-node-1
discovery.seed_hosts: test-node-1
```
3. start opensearch service
4. check logs

**Expected behavior**
Cluster state becomes green.

```
 ~# curl --silent --connect-timeout 3 --header 'Host: stats' --write-out '%{http_code}' "http://<local-ip>:9200/_cluster/health?pretty=true"
{
  "cluster_name" : "cluster",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 4,
  "active_shards" : 4,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 3,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 57.14285714285714
}
```

**Plugins**
Basic installation.

**Screenshots**
%

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (updates installed)
 - Version 2.9.0

**Additional context**
In the logs of opensearch I am able to discover the following informations:
```
[2023-08-02T11:07:51,126][ERROR][o.o.s.u.SecurityAnalyticsException] [test-node-1] Security Analytics error:
org.opensearch.ResourceAlreadyExistsException: index [.opensearch-sap-pre-packaged-rules-config/CWaJHMTdTlmZSg9zl5rPaA] already exists
```

```
[2023-08-02T11:07:51,149][WARN ][o.o.s.SecurityAnalyticsPlugin] [test-node-1] Failed initializing prepackaged rules
org.opensearch.securityanalytics.util.SecurityAnalyticsException: index [.opensearch-sap-pre-packaged-rules-config/CWaJHMTdTlmZSg9zl5rPaA] already exists
```

```
[2023-08-02T11:07:51,196][WARN ][o.o.s.SecurityAnalyticsPlugin] [test-node-1] Failed to initialize LogType config index and builtin log types
```

```
[2023-08-02T11:07:52,152][INFO ][o.o.c.r.a.AllocationService] [test-node-1] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.opensearch-sap-log-types-config][0]]]).
```

Complete log can be found at: https://justpaste.it/c9c32

**Comment by dbwiddis** [comment]
```
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 4,
  "active_shards" : 4,
  "unassigned_shards" : 3,
```
From [the docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html):
> A yellow cluster status means the primary shards for all indexes are allocated to nodes in a cluster, but the replica shards for at least one index aren't. 

You only have one node, but the replica shard needs to be on a different node.

**Comment by techsk8** [comment]
indeed, the problem is solved on opensearch 2.10 and 2.11

**Comment by HoffmannTom** [comment]
The warning "Failed to initialize LogType config index and builtin log types" as mentioned in the issue title is still present in version 2.11
The cluster status is green though.
